### ISSUE TITLE
Lockup on Macbook Pro 2012

### ISSUE THREAD

**Issue by ChrisEddy** [webmixedreality/exokit#115]
It runs at about 50- 60fps it looks like, installs and opens fine... I tried to use "command + q" which is quit application on apple keyboards... it froze really badly and i couldn't escape the freeze. Had to hold down power button. Only happened once so far. Going to try and reproduce.

13 inch Macbook Pro mid 2012 model
2.9ghZ i7 dual core processor(4 threads tho)
16 gigs of 1600mhz RAM
SSD
Intel HD Graphics 4000 (1536mb)

**Comment by ChrisEddy** [comment]
2nd attempt:

Loads fine like before, walking around moving controllers all works... 
I loaded a reality tab named "konterball" from the App menu and the whole world went black except for the Menu and then it locked up, froze my computer and couldn't escape, all keyboard commands are frozen. Held power down hard reset to escape.

BTW there is no error console launched with the Exokit browser like there is in windows.

**Comment by modulesio** [comment]
I tried this on MBA 2017 and got no lockups of any sort.

However I did find OSX-specific GLFW context management problems with reality tabs. Now that reality tabs are a thing that exist on Windows it might be time to look at what's going wrong on OSX.

Filed these as separate issues: #116, #117, #118, #119.

Some of these seem to be related to the recent introduction of Obj-C code (cc @shawwn).

**Comment by ChrisEddy** [comment]
Yeah i posted my computer specs for context here too... 1500mb of integrated CPU graphics is powering my machine so maybe i cant handle it.

**Comment by modulesio** [comment]
Closing stale issue.
