### ISSUE TITLE
Labsound sigsegv on Ubuntu build.

### ISSUE THREAD

**Issue by ChrisEddy** [webmixedreality/exokit#125]
## My System: 
Ubuntu 18.04 LTS
VirtualBox
Fully updated OS
Node v10.4.1

## Scenario
When using `./exokit.sh -h`:

Error:
`node: symbol lookup error: /home/chris/Downloads/exokit-master/build/Release/exokit.node: undefined symbol: snd_card_next`

**Comment by modulesio** [comment]
This looks like missing `RtAudio`, which should be a required dependency [listed in the docs](https://docs.webmr.io/docs/devsetup.html#linux-dependencies).
