### ISSUE TITLE
can't run on windows 7. error from cmd

### ISSUE THREAD

**Issue by Rolandas1369** [webmixedreality/exokit#129]
C:\exokit>exokit.cmd
internal/modules/cjs/loader.js:731
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: error: -1073741795\\?\C:\exokit\build\Release\exokit.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:731:18)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\exokit\native-bindings.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)

**Comment by modulesio** [comment]
If this persists on the latest release on Windows 7 (release v0.0.357), it looks like a possible dll dependency is not resolved.

Would you be able to use something like http://www.dependencywalker.com to submit a report of unresolved dll symbols for the binary build\Release\exokit.node on this system?

I’m suspecting dependency walker would show what is not being resolved so we could fix it. :+1:

**Comment by Rolandas1369** [comment]
Dependency walker:
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by shawwn** [comment]
@Rolandas1369 Can you join us in Slack? https://exoslack.now.sh/

Or discord: https://discord.gg/vEVfh8Z

**Comment by modulesio** [comment]
That seems to confirm missing import. Is there a way to paste the full report to a text file, or screenshot exactly which falls are missing?

**Comment by modulesio** [comment]
Provided by @Rolandas1369:

![falls](https://user-images.githubusercontent.com/6926057/41737019-181d9812-755c-11e8-872e-801c503e0ae8.png)

**Comment by modulesio** [comment]
It could be missing VS redistributables: https://stackoverflow.com/questions/17023419/win-7-64-bit-dll-problems

**Comment by modulesio** [comment]
Wondering we we could just add the VS2017 redist to the inno setup: https://stackoverflow.com/questions/24574035/how-to-install-microsoft-vc-redistributables-silently-in-inno-setup

**Comment by modulesio** [comment]
@Rolandas1369 Attempted fix is in https://github.com/webmixedreality/exokit/releases/tag/v0.0.359. It came via https://github.com/webmixedreality/exokit/pull/134.

It would be great if you could test if it runs on the Windows 7 system. 👍

**Comment by modulesio** [comment]
If this is still an issue, please re-open!
