### ISSUE TITLE
Electron integration

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#135]
It’s been a common request to integrate Exokit with existing electron apps.

According to recent releases the versions are coming closer in sync:

https://electronjs.org/releases#3.0.0-beta.1

**Comment by modulesio** [comment]
I think @shawwn did some awesome work in this area, but the contribution status of that code is unclear.

**Comment by shawwn** [comment]
It was actually @sheminusminus, not me. You could ask her if she'd be willing to PR it.

**Comment by modulesio** [comment]
@sheminusminus Is there any code that can be contributed re: running on Electron? It's a common ask.

**Comment by sheminusminus** [comment]
@modulesio Potentially. Is the common ask more so for general exokit-electron IPC, or for the ability to use exokit as an electron app front-end?

**Comment by modulesio** [comment]
It's the latter that's missing, embedding exokit into electron.

For the IPC we're working on that separately, figuring what the right XR-thinking API is.

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated. Electron integration was removed in #617.
