### ISSUE TITLE
Oculus DK1 support

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#14]
https://developer.oculus.com/downloads/package/oculus-sdk-for-os-x/

I have an Oculus DK1 headset. It might be good to support that. I don't know whether DK2 is already supported.

**Comment by modulesio** [comment]
I would skip the DK's and just cut it at release honestly...

**Comment by modulesio** [comment]
It's an OpenVR thing. I'm not sure if there's resources to support older DK's.

I think if it's to be supported then it would come down to openvr/backing lib, rather than being on our plate.
