### ISSUE TITLE
Site doesn't work

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#143]
https://two.js.org/examples/three-extrusion.html

**Comment by modulesio** [comment]
```
THREE.WebGLProgram: Could not initialise shader.
gl.VALIDATE_STATUS false
gl.getError() 1282
THREE.WebGLProgram: gl.getProgramInfoLog() Fragment info
-------------
0(138) : error C1008: undefined variable "unique_fragColor"
(0) : error C2003: incompatible options for link
```

This is a shader translation issue most likely. That happens in [native-bindings.js](https://github.com/webmixedreality/exokit/blob/f5083fa3b783dce0878a38ad787f1103b6d518f2/native-bindings.js#L10).

**Comment by modulesio** [comment]
Fixed with https://github.com/modulesio/webgl-to-opengl/commit/7af62c288e92a3214f9a6c52ccfed9eac9a6b6f9 + https://github.com/webmixedreality/exokit/commit/d2db643490edccea52406c73da01a2e7aef6b8df.
