### ISSUE TITLE
Break up core.js

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#145]
Most of the "browser" part of the Exokit browser is in [core.js](https://github.com/webmixedreality/exokit/blob/master/core.js).

There is no good reason for it being contained in one file; it's convenient but it makes the code seem scarier than it is to newcomers.

`core.js` should already have a reasonably coherent layout and factoring; we just need to classify the pieces and break them up into their own files that are `require`d in.

A lot of this is just copy-paste.

### File/directory sections

This is a rough idea for the files/directories we'd probably want:

- Network
- GL
- Audio
- Video
- Canvas
- Scripting contexts
- VR
- XR
- Magic Leap
- Leap Motion
- Events
- DOM
- Observers
- Window
- Document
- Bootstrap
- Runtime loop/queues

**Comment by shawwn** [comment]
I prefer core.js being in a single file. It makes it much easier to grep, it's clear which code runs in a window worker and which code doesn't, and it makes the process of bootstrapping HTML types easier. For example, HTMLVideoElement's implementation is redefined; if this was moved to a separate file, it would be unclear where this redefinition should be placed on disk or what it should be called. It would also make the logic far more difficult to follow.

**Comment by ngokevin** [comment]
Thanks for filing! I haven't started working on the project or anything but benefits of splitting up IMO could be:

- Being able to see what parts of the codebase were changed in Git (imagine `core.js ++500 additions --250 deletions` versus `vr.js +250 additions xr.js +200 additions).
- Not having to jump up and down a single file when editing multiple parts of it.
- Easier to unit test individual modules.
- Split out and organize parts of the code to make it easier to find things (e.g., what parts run in a window worker and what parts doesn't).

When reading core.js, I'm not sure what's contained inside it or what structure it has without reading the whole thing but would be easier to get a picture if I could see as directories + files.

**Comment by shawwn** [comment]
> Easier to unit test individual modules.

This is a good point.

Would you be interested in setting up some basic unit tests?

**Comment by ngokevin** [comment]
Yeah, after I dig in a bit and get set up, I think I'd get to playing with some unit tests.
