### ISSUE TITLE
Make Exokit streamable

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#15]
Streaming is a big thing. I spend more time on Twitch than I'd care to admit.

It would be good to harness that wave by adding stream integration into Exokit.

The integration should be developer-focused at first, since those are who we want streaming Exokit anyway. Maybe we can bundle OBS and make it a one-click setup?

**Comment by shaneharris** [comment]
in windows 10 you can use the game bar to record/stream. Windows key and g

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated.
