### ISSUE TITLE
require("exokit") + exokit.load() does not work

### ISSUE THREAD

**Issue by etiennepinchon** [webmixedreality/exokit#17]
Embedding Exokit in a nodejs project or running it directly from the node prompt does not work.

Code snippet:

Enter `node` and then paste
```javascript
const exokit = require("exokit");
exokit.load('https://threejs.org/examples/#webgl_animation_cloth', {})
```

**Comment by modulesio** [comment]
Should be fixed in https://github.com/webmixedreality/exokit/commit/2d3a67ccc361f2dece32f8fb1ceab42aa379acd6.

Also cut a new release with it: https://github.com/webmixedreality/exokit/releases/tag/v0.0.246
