### ISSUE TITLE
WebGL2: queries

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#189]
Part of WebGL2 to add.

https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/beginQuery

**Comment by Palmer-JC** [comment]
Even though BabylonJS does not use queries, the existence of using WebGL2 is conditional on the success call of `gl.deleteQuery()`

Looking around, it looks like this would need to be added to the `WebGL2RenderingContext` object in `webgl.cc`:
```c++
  // prototype
  Nan::SetMethod(proto, "createQuery", glCallWrap<CeateQuery>);
  Nan::SetMethod(proto, "beginQuery", glCallWrap<BeginQuery>);
  Nan::SetMethod(proto, "endQuery", glCallWrap<EndQuery>);
  Nan::SetMethod(proto, "deleteQuery", glCallWrap<DeleteQuery>);
```
with implementations:
```c++
// reference used https://www.khronos.org/registry/OpenGL-Refpages/es3.0/
NAN_METHOD(WebGL2RenderingContext::CreateQuery) { // adapted from CreateBuffer
  GLuint queryId;
  glGenQueries(1, &queryId);

  Local<Object> queryObject = Nan::New<Object>();
  queryObject->Set(JS_STR("id"), JS_INT(queryId));
  info.GetReturnValue().Set(queryObject);
}

NAN_METHOD(WebGL2RenderingContext::BeginQuery) { // adapted from BindBuffer
  GLenum target = info[0]->Int32Value();
  GLuint query = info[1]->IsObject() ? info[1]->ToObject()->Get(JS_STR("id"))->Uint32Value() : 0;

  glBeginQuery(target, query);
}

NAN_METHOD(WebGL2RenderingContext::EndQuery) {
  GLenum target = info[0]->Int32Value();
  glEndQuery(target);
}

NAN_METHOD(WebGL2RenderingContext::DeleteQuery) { // adapted from DeleteBuffer
  GLuint query = info[0]->IsObject() ? info[0]->ToObject()->Get(JS_STR("id"))->Uint32Value() : 0;

  glDeleteQueries(1, &query);
}
```

I also see that a `glbindinit.h`, not called by `webgl.cc` needs to have entries like:
```c++
	_gl->Set(v8::String::NewFromUtf8(isolate, "createQuery"), v8::FunctionTemplate::New(isolate, __createQuery));
	_gl->Set(v8::String::NewFromUtf8(isolate, "beginQuery"), v8::FunctionTemplate::New(isolate, __beginQuery));
	_gl->Set(v8::String::NewFromUtf8(isolate, "endQuery"), v8::FunctionTemplate::New(isolate, __endQuery));
	_gl->Set(v8::String::NewFromUtf8(isolate, "deleteQuery"), v8::FunctionTemplate::New(isolate, __deleteQuery));
```
I am not even sure how to compile this, `npm update`?  If this is useful, I can also provide the same for samplers & other WebGL2 issues.

**Comment by Palmer-JC** [comment]
Also looking further down in the WebGL2 standard, I see 3 methods not listed above.  I had done them, but removed them.  I edited first comment adding `GetQuery, GetQueryParameter, & IsQuery`

**Comment by Palmer-JC** [comment]
Well, I usually keep on going without waiting when I ask a question.  I figured out you had a build script.  I fixed all my errors.  

I do not know that this code worked beyond, `if (!gl.deleteQuery)` equates to true.  I can now run any Babylon.JS 4.0 scene.  I get WebGL2 context, and it is working.  Should I PR this?

**Comment by modulesio** [comment]
@Palmer-JC Yes, please open a PR!

From an initial glance the above looks like you found all the right places. I'd love to test it out on my end and review the code in context.

**Comment by Palmer-JC** [comment]
Done for today, tomorrow.  Also, this depends on the [WebGL2 fix pr](https://github.com/webmixedreality/exokit/pull/771)

**Comment by modulesio** [comment]
Closed by https://github.com/webmixedreality/exokit/pull/821
