### ISSUE TITLE
Youtube player

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#20]
Would be nice if this worked:

```
exokit https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

It could open the video in desktop mode, with enter VR/AR capability.

**Comment by shaneharris** [comment]
Could this be covered with electron? Some proxy for youtube could allow is to wrap an equirectangular video around a sphere too for 360 videos. Not limited to youtube either we could live stream from a 360 camera on twitch for instance.

**Comment by modulesio** [comment]
I was thinking less a proxy, and just a generic site loader if the site isn't VRable. Using electron.

Those are all cool ideas but I'm not sure if they belong in the core -- fixing up any issues in the electron API and unlocking user code to implement these ideas is probably the way to go.

I'll close this issue because it's kind of ill-defined.
