### ISSUE TITLE
Does not start on Linux without GLIBC

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#25]
![nodebuild](https://user-images.githubusercontent.com/6926057/39084886-d6ac40dc-4549-11e8-950c-6d9ddf7ace07.png)

**Comment by modulesio** [comment]
Seen on `Ubuntu 16.04.4 LTS`.

**Comment by jteneycke** [comment]
Came across an issue in https://github.com/ValveSoftware/openvr/issues/549 on my way to try figuring out #34 which seems related to this one. I'm a bit fuzzy to grok it all right now, but it seems worth linking for anyone more familiar with this territory.

**Comment by modulesio** [comment]
This one seems a toolchain issue specific to Ubuntu: I'm guessing the [version used by Travis](https://github.com/webmixedreality/exokit/blob/master/.travis.yml) seems to not be the same as the one used by Ubuntu.

The exe in the OP is I believe I binary release from https://github.com/webmixedreality/exokit/releases.

It would be interesting to know if this issue is also present with a local `npm install` of the repo, on an Ubuntu host. If it's not then it's a build issue. If it is then it would probably be a more general Linux problem.

**Comment by chrislatorres** [comment]
Tested on Ubuntu 18.04, confirmed fixed.
