### ISSUE TITLE
README: browser/engine split

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#271]
To clarify confusion about the project structure we decided on an engine/browser split.

In this mindset the core code is considered "engine" possibly embeddable in many different environments and technologies, like Electron, ARCore, Magic Leap, etc.

Various immersive UIs, Reality Tabs, forward-thinking experimental APIs and such could be a layer on top that, using the "engine" technology and packaging it up for consumption. In our case that's "Exokit browser" but could be many others using the same "Exokit engine".

We just need to clarify this in the README.md

**Comment by ChrisEddy** [comment]
I like this direction! I'll help with Readme soon
