### ISSUE TITLE
OSX: bad viewport size

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#30]
![image](https://user-images.githubusercontent.com/59632/39564483-0f808c7c-4e7a-11e8-868f-0a3900fd19f2.png)

(Notice it's ~2x what it should be.)

**Comment by modulesio** [comment]
It must be a `.dPR` issue; assuming it's `2` on this system?

**Comment by modulesio** [comment]
Also does this one repro on any site, or just the home environment layer?

**Comment by modulesio** [comment]
@shawwn I attempted a fix at https://github.com/webmixedreality/exokit/commit/8ee971b6a39b901d603aff6ffb64b6f208c3a9da, and cut a release. Can you verify + close?

**Comment by modulesio** [comment]
Assuming it's fixed 👍 .
