### ISSUE TITLE
Reality tabs break-out from browser

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#306]
Right now reality tabs are [contained in `exokit-home`, or the "browser" part](https://github.com/webmixedreality/exokit-home/blob/7f1247b45cbf98d370b0a6b3228617c7a3b0ef9f/js/ScreenQuad.js#L19).

To decouple the browser more from the core engine, we should probably move the key features into the engine itself. One of those features is reality tabs.

**Comment by modulesio** [comment]
For this I think the right dev approach is to first standardize on `iframe` (or similar) loading being a reality tab, regardless of the site.

And then move over any functionality from `exokit-home` to enable that, when running a site that is not `exokit-home`.

**Comment by modulesio** [comment]
And finally, I think this should be a dead-simple API -- any shaders for composition and such should be hidden away inside exokit core, not managed by the site.

We can probably just use the WebVR/WebXR layers APIs for this so we're not inventing anything.

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated. This was added in #547.
