### ISSUE TITLE
Reality tabs: bump layers count

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#307]
Right now reality tabs are limited to two layers, for no good reason other than that was [the easy way to write the shader](https://github.com/webmixedreality/exokit-home/blob/7f1247b45cbf98d370b0a6b3228617c7a3b0ef9f/js/ScreenQuad.js#L19). The only limit to how high we can go is how many textures we can pack at once and how fast the hardware can blend it.

We could make the cap at least `8` to start.

**Comment by chrislatorres** [comment]
It looks like reality tabs [layers](https://github.com/webmixedreality/exokit/pull/547/files#diff-9072aaf78a49fe573d7263fd2ac67503R153) are unlimited since #547 and the performance is being improved by #760.

**Comment by modulesio** [comment]
That is correct. Closing.
