### ISSUE TITLE
Electron test: texture parameters out of sync

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#342]
As seen in https://github.com/webmixedreality/exokit/blob/master/examples/electron_tests.html, we get texture parameters not going through.

Flipping through the options with `keyup` we get certain texture settings resulting in missing blits and such.

![capture 12](https://user-images.githubusercontent.com/6926057/43932320-5e3c1f5e-9c11-11e8-9c84-7d871d1023f6.PNG)

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated. Electron integration was removed in #617, and was replaced with Chromium Embedded Framework (CEF).
