### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by shawwn** [webmixedreality/exokit#343]
For implementing gamepad support, it seems to make sense to run a separate process that monitors gamepad inputs and sends messages to exokit. I prefer this architecture rather than bogging exokit down with even more functionality. It's also more stable, considering that a crash in one module won't affect the overall system.

This issue is to collect some thoughts about a sort of "standard interface" for this type of work. Refs:

[Composable Reliability for Asynchronous Systems](https://www.usenix.org/system/files/conference/atc12/atc12-final206.pdf)

[The Magic Ring Buffer](https://fgiesen.wordpress.com/2012/07/21/the-magic-ring-buffer/)

[share-node-memory npm package, for named shared memory](https://github.com/shawwn/share-node-memory)

**Comment by modulesio** [comment]
I disagree with that approach, because it's not compatible with other platforms that don't allow or simply don't have `fork`. It also adds another IPC channel and asynchony/potential race, and another context switch for a project that's based around having a well-controlled synchronous render loop.

**Comment by shawwn** [comment]
It doesn't rely on fork. It only relies on spawning child processes, and sharing blocks of memory with them. Every OS supports that.

**Comment by modulesio** [comment]
Child process uses fork, and as far as I know is banned from iOS.

**Comment by shawwn** [comment]
Hmm, you're right. On the other hand, since the child processes are written in javascript, it's easy to collapse all of them into a single address space for platforms that don't support child processes.

**Comment by modulesio** [comment]
So why play multiprocess tricks if the inline solution works everywhere?

**Comment by modulesio** [comment]
I think this is a special case of how to do extensibility. I don't think "multiprocessing" is in scope for the core, though I'm interested in supporting the case of integrating modules that do it.

That should be pretty easy right now with node modules, but if there's a problem we hadn't considered there please open another issue for it.
