### ISSUE TITLE
Body clientHeight not correct

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#347]
Follow-up to https://github.com/webmixedreality/exokit/pull/345#issue-207752310.

Exokit is naive about how it [computes `Element.clientHeight` right now](https://github.com/webmixedreality/exokit/blob/57ddbec6e898af1247bac2030da78a30dd698dd2/src/DOM.js#L13195). It's just the GL/canvas height, which is not correct and can be problematic if the site is reading this.

@ngokevin could you point to the repro case that should work? The one in https://github.com/webmixedreality/exokit/issues/252 is just logging `canvas`.

**Comment by ngokevin** [comment]
Here is a reproduction case: https://hospitable-swordfish.glitch.me/

It will log window.innerWidth/Height and document.body.clientWidth/Height

In the A-Frame scene, the purple square should track the mouse position.
