### ISSUE TITLE
WebVR mode retains WebXR globals

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#349]
We have the `-x webvr` flag to switch to legacy `WebVR` API-only mode. This disabled `nagivator.xr` correctly but it retains the WebXR globals.

This behavior confuses some WebXR polyfills, which see the globals and refuse to overwrite them, making the site not work at all in this case (when it could).

**Comment by ngokevin** [comment]
This is no longer an issue:

```
 917   // WebVR enabled.
 918   if (['all', 'webvr'].includes(GlobalContext.args.xr)) {
 919     window.navigator.getVRDisplays = function() {
 920       return Promise.resolve(this.getVRDisplaysSync());
 921     }
 922   }
 923
 924   // WebXR enabled.
 925   if (['all', 'webxr'].includes(GlobalContext.args.xr)) {
 926     window.navigator.xr = new XR.XR(window);
 927   }
 928
```

**Comment by modulesio** [comment]
I'm not sure, I think the trigger for this issue was an engine detecting `window.XR`, which is still unconditional:

https://github.com/webmixedreality/exokit/blob/d15da6e1b755350f5f3cd78963faa103c6e5c367/src/core.js#L1341
