### ISSUE TITLE
Missing Element.children property

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#384]
Exokit: Version 0.0.420
OS: WIndows 10 x64
Not sure if this matters so feel free to close. 

I sometimes would recurse a dom tree using the `Element.children` property but after using `Element.insertAdjacentHTML` on the parent the children were not updated and `Element.children.length` was 0;

Workaround: I used `Element.childNodes` and filtered on the `Node.nodeType === 1` (ELEMENT_NODE) instead.

Shim: If we do want to shim this behavior here is a working example - https://github.com/darktrojan/shim.js/blob/master/shim.js#L101

**Comment by ngokevin** [comment]
Did you wait a tick?

**Comment by shaneharris** [comment]
just throw it into the event loop? yeh i wrapped it in a setTimeout just incase

**Comment by shaneharris** [comment]
The next tick did the trick - https://github.com/webmixedreality/exokit/issues/385
