### ISSUE TITLE
Aframe Element properties, object3D, components

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#385]
Exokit: Version 0.0.420
OS: WIndows 10 x64
Once again this might be a mute issue but i remember reading this was considered a viable way to access components on an aframe entity. 

I found that the aframe element property `Element.components` was never set. SO for instance if i wanted to get the position on the Z i could do `this.el.components.position.z`. Maybe its best to access them a different way. 

Workaround: I used `Element.getAttribute('position').z` instead which worked ok.

**Comment by ngokevin** [comment]
Show full code, most likely it's a code issue. A-Frame definitely works, and that would be a major obvious issue if that didn't.

**Comment by shaneharris** [comment]
Yep ill get a basic example together. This also might only be the case with dynamic html inserted with `Element.insertAdjactentHTML` as i was also using that sorry i forgot to mention.

**Comment by shaneharris** [comment]
My bad! i had tried setTimeout and i hadn't worked before. It did this time though. For reference here is the code i used to test. Ill close this and the other one as it was the same.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://aframe.io/releases/0.8.2/aframe.min.js"></script>

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", ()=> {
            let scene = document.querySelector('a-scene');
            scene.addEventListener('loaded',()=>{
                scene.insertAdjacentHTML('afterbegin',`
                    <a-box id="theBox" color="red" position="0 0 -4"></a-box>
                `);
                console.log(document.getElementById('theBox').components);
                setTimeout(()=>console.log(document.getElementById('theBox').components),0);
            })
        });
    </script>
</head>
<body>
    <a-scene>

    </a-scene>
</body>
</html>```
