### ISSUE TITLE
docs.webmr.io improvements

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#44]
There's some delicious low-hanging fruit in our docs site 🍒. Although there is a good framework, we could both clean up and expand the site for commonly asked pointers.

We currently use [`docsify`](https://github.com/QingWei-Li/docsify) as a [Github page]() for the docs, but that's amenable to change. Whatever we use should be automatic and 🤖.

### Frequently asked docs

- Can I see some screenshots and videos?
- Which sites can I open right now?
- How do I run multiplayer?
- How do I plug in to my node.js app?
- Does it work with electron?
- Why doesn't https://youtube.com/ open?
- What is the "why" of the project?
- I have bug X.
- How do I run it in Magic Leap?
- How do I run it with Leap Motion?
- When is `1.0`?

### Chores

- Remove the huge cover page?
- `<title/>` tag?
- `<meta/>` tags?

### How to fix these

Submit a PR to [webmixedreality/webmr-docs](https://github.com/webmixedreality/webmr-docs) 🥇

**Comment by shaneharris** [comment]
Is this now solved with the new website?

**Comment by modulesio** [comment]
It's an ongoing process. But yeah, many of these points are no longer really relevant/have better avenues to address them, like video tutorials.
