### ISSUE TITLE
Instanced geometry crashes exokit on ML One.

### ISSUE THREAD

**Issue by mvilledieu** [webmixedreality/exokit#443]
Using Instanced geometry causes Exokit to crash when trying to run it on ML One. 

`I exokit  : \.node-gyp\10.9.0\include\node\node_object_wrap.h:50: static T *node::ObjectWrap::Unwrap(v8::Local<v8::Object>) [T = WebGLRenderingContext]: assertion "handle->InternalFieldCount() > 0" failed
`

**Comment by modulesio** [comment]
This looks like a bug we fixed yesterday. What is the URL? Are you running `0.0.459` or higher?

https://github.com/webmixedreality/exokit/releases/tag/v0.0.459

**Comment by modulesio** [comment]
Bugfix PR: https://github.com/webmixedreality/exokit/pull/439

**Comment by ngokevin** [comment]
Yeah, most likely running an non-master build.

**Comment by mvilledieu** [comment]
My bad I wasn't running the last version, that's fixed thanks so much guys.
