### ISSUE TITLE
.wav audio element hangs Exokit.

### ISSUE THREAD

**Issue by ngokevin** [webmixedreality/exokit#449]
https://webvr.soundboxing.co

Spent a few hours trying to narrow it down. It creates a sound pool (50 audio objects of a sound), which the initialization of hangs Exokit. Either the network or audio code.

Checking it out.

**Comment by ngokevin** [comment]
Simplifed example with source: https://fluffy-visitor.glitch.me/

**Comment by ngokevin** [comment]
Actually, it just hangs with this .wav file:

ttps://cdn.glitch.com/aa3c5e02-ba30-4eac-a7e8-d9941c736eaa%2Fui_scifi_hightech_error.wav?1536551986024

**Comment by modulesio** [comment]
Yeah I just repro'd this in CLI:

```
a = new Audio(); a.src = 'https://cdn.glitch.com/aa3c5e02-ba30-4eac-a7e8-d9941c736eaa%2Fui_scifi_hightech_error.wav?1536551986024'
```

**Comment by ngokevin** [comment]
Fixed in https://github.com/webmixedreality/exokit/pull/287/files

**Comment by ngokevin** [comment]
Gonna try to take a short journey into debugging this, will be a fun C++ challenge.

**Comment by modulesio** [comment]
Not sure if there is any relation to https://github.com/webmixedreality/exokit/pull/287. That issue was mostly about garbage collection and callbacks scoping of `AudioBuffer`, but this looks more like just an `Audio` load lock.

Here is the main place for loading `Audio`: https://github.com/webmixedreality/exokit/blob/db685b67b3abaee20f50c3e6e278f3ddef185274/deps/exokit-bindings/webaudiocontext/src/Audio.cpp#L48

**Comment by ngokevin** [comment]
Yeah I just arrived at the same line xD:

`shared_ptr<lab::AudioBus> audioBus(lab::MakeBusFromMemory(buffer, false, &error));`

**Comment by ngokevin** [comment]
Still poking at it, was trying to set up some debugging flow with LabSound -> node-native-audio-deps -> Exokit, but just testing purely within LabSound repo now.

**Comment by modulesio** [comment]
Yeah, if it's a call to LabSound that's hanging, it could possibly be an issue entirely in the LabSound repo, which would need to be rebuilt.

**Comment by ngokevin** [comment]
What's the build step for node-native-audio-deps to get the ZIPs? Gonna try to bump LabSound, I don't know if there have been any modifications to it, but the new signature for `MakeBusFromMemory` is `std::shared_ptr<AudioBus> MakeBusFromMemory(const std::vector<uint8_t> & buffer, std::string extension, bool mixToMono)`. At least loading the WAV from file works in LabSound master.

**Comment by ngokevin** [comment]
Cool. How does your LabSound compare in functionality to the upstream one? Which parts are ahead of the other and vice-versa?

**Comment by modulesio** [comment]
Mostly adding new node types, like `ScriptProcessorNode`, some panners, and I think maybe `AudioBuffer`. This required going in and adding deeper locking functionality.

I would have to trace upstream to find out what's changed but for the most part I think that fork is a superset.

**Comment by modulesio** [comment]
I _think_ it was because we already have ffmpeg, which has larger coverage and also MP3, which I think `libnyquist` does not.

**Comment by ngokevin** [comment]
Narrowed it down to hanging on call to ffmpeg `avformat_find_stream_info`:

https://github.com/modulesio/LabSound/blob/master/labsound/src/extended/AudioFileReader.cpp#L80

**Comment by ngokevin** [comment]
Think I got it! https://github.com/modulesio/LabSound/pull/12

**Comment by modulesio** [comment]
Awesome, that would probably do it 👍
