### ISSUE TITLE
Support loading from p2p web

### ISSUE THREAD

**Issue by RangerMauve** [webmixedreality/exokit#452]
Hi, I love the ideas behind this project. I really like the approach of having a VR-first browser, and I think it's very much needed to move WebVR forward.

That being said, publishing WebVR content still requires people to rely on hosting providers and adds more friction for publishing new content.

I've been working an a browser-like environment called [Webrun](https://github.com/RangerMauve/webrun) which takes a similar approach with creating new JS contexts and injecting web globals.

As part of the environment, I added support for the [dat protoco](https://datproject.org/) which is a peer to peer protocol that allows people to create websites by creating a unique URL that allows others to download their content from the p2p network. This protocol is being used in the [Beaker Browser](https://beakerbrowser.com/) which allows people to create web content without relying on hosting providers to serve it. This allows people to have more control over their data and to make it easier for people to publish on the web. Here's [an article](https://hacks.mozilla.org/2018/08/dweb-serving-the-web-from-the-browser-with-beaker/) about it posted on Mozilla Hacks.

Mozilla has recently started [implementing APIs](https://github.com/mozilla/libdweb) that would enable the peer to peer web to flourish, and Chrome seems to be slowly following behind in doing the same thing.

I think that VR in cyberpunk media is often touted as allowing people to create their own virtual environments that they have full control over. I think that this fits in perfectly with the peer to peer web and with how Dat works.

Would you be interested in having support for loading websites over Dat as well as providing the DatArchive API which allows developers to create and modify new (or existing) Dat archives from within a web page? I've implemented support for it using the [dat-node](https://github.com/beakerbrowser/dat-node) library and it's been working like a charm.

What this will enable is self-modifying VR spaces. A person can open an existing VR Dat website, create their own editable copy, and use tools from within the VR website to modify it. This will potentially be revolutionary in allowing more casual users to create and host their own VR worlds without having to rely on third party hosts to allow them to use them.

**Comment by modulesio** [comment]
Dat’s architecture done worse was my college thesis back in the day ;).

I’m for it; it’s defintiely in line with the project to experiment with things like first class dat:// or peer api exposure.

I’m loaded with tasks this next week but it would be awesome to try an integration. What would the api surface look like here?

**Comment by RangerMauve** [comment]
Basically, we'd need to find everywhere where you load stuff through HTTP (script tags, images, audio, etc), and load the content through `dat://`, next we'd need to add another browser global: window.DatArchive, which would allow JS access to create and modify archives.

Ideally, you'd need some UIs for managing your archives and for "selecting" and archive, but I think that can wait until after the initial implementation.

`@beaker/dat-node` does all the heavy lifting for loading archives / caching their data / finding peers, so that part should be easy.

I think a good progression would be:

- [ ] Load the index.html from a `dat://` site
- [ ] Load script tags on the page from the archive
- [ ] Load images / audio / video / etc from the archive
- [ ] Wrap `fetch()` so that it will accept `dat://` URLs

At this point it should enable most web VR uses for loading scenes

After, you can probably yank the DatArchive polyfill right from [webrun](https://github.com/RangerMauve/webrun/blob/master/polyfills/makeDatArchive.js) and do the following:

- [ ] provide `window.DatArchive`
- [ ] provide a UI for `DatArchive.selectArchive()` and `DatArchive.create()`
- [ ] provide the experimental [datPeers](https://beakerbrowser.com/docs/apis/experimental-datpeers) API which allows you to discover and communicate with peers in a fully p2p manner (no central servers for messaging people that are viewing the same `dat://` website as you)
- [ ] provide the experimental [library](https://beakerbrowser.com/docs/apis/experimental-library) API to enable VR apps to be built to manage the dats you've created locally or are seeding for someone else.

At this point people will be able to ditch a lot of the legacy web and start publishing stuff on the peer to peer web. People can set up virtual worlds, and others can copy them and remix them and share them again. Somebody will probably figure out an elegant way to do multiplayer over the `datPeers` API and we'll be able to have people spin up their own interactive worlds without the need for servers.

**Comment by modulesio** [comment]
It's already the case that `fetch` is used for most things in Exoklit, including getting HTML, scripts, and media. So adding that support to [`widow-fetch`](https://github.com/modulesio/window-fetch) would unlock most things above.

I think XHR goes through a separate code path so that might be duplicate work, but basically the same thing.

And yeah if there is a polyfill for `DatArchive` that sounds like it could be mostly drop-in. +1 for JS.

**Comment by RangerMauve** [comment]
I'm going to need to create a proper `fetch()` implementation for webrun that supports Dat, so I'll shove that into an external module that uses `dat-node`. So far I'm just using [node-fetch](https://www.npmjs.com/package/node-fetch). Then we should be able to replace the existing fetch implementation with it. :D

I'm going to be a bit busy this week, but I think I could make progress on it next week. Would you mind pointing me to where you initialize `fetch`?

**Comment by modulesio** [comment]
[Exposing `fetch` here](https://github.com/webmixedreality/exokit/blob/fbaaed9681a48c88e3616d90afc500c54cacecc5/core.js#L962). That could almost be a direct ` = fetch` , but there is some native prototypes conversion there for shifting between window contexts, and `Blob` url handling.

[`window-fetch`](https://github.com/modulesio/window-fetch) is actually a fork of `node-fetch`.

**Comment by RangerMauve** [comment]
Ok cool, then I'll make a module that takes a `fetch` implementation and a `dat-node` instance as parameters and returns something that has the same API as `fetch`. Then you can just change the require and it'll be have pretty much the same way.

**Comment by RangerMauve** [comment]
Oh one more thing, do you have a cache folder defined somewhere that I can put dat archive data into?

**Comment by modulesio** [comment]
Interesting, I like the wrapping technique to separate the implementation.

We have a [`dataPath` that can contain this](https://github.com/webmixedreality/exokit/blob/fbaaed9681a48c88e3616d90afc500c54cacecc5/core.js#L1063).  Can be like `.dat` under that for now.

**Comment by ngokevin** [comment]
Seems risky to maintain a whole new protocol going forward that won't see much usage. Hosting websites is free and easy nowadays (Glitch, GitHub, Neocities, S3). For VR/AR, you probably prefer guaranteed assets to come down fast.

Perhaps a good approach is allow it on the lower level: work on adding Extension support so developers/forkers can expose APIs they want (e.g., `window.datFetch`).

**Comment by modulesio** [comment]
What's the risk we're talking about here?

I think it's already pretty easy to add protocols and such, so I'd be more interested in making that development smooth than having another API for extensions. But maybe if extensions were just an npm module that could work.

I think probably `electron`/HTML rendering might fall under this same concern.

**Comment by ngokevin** [comment]
Just maintenance overhead over value provided. I think Electron/HTML rendering is more immediately useful over an API propped on philosophy over pragmatism.

**Comment by RangerMauve** [comment]
> Just maintenance overhead over value provided.

There really won't be that much maintenance required given dat support only requires a minor, and backwards compatible, change to fetch, and a new global variable. Both of which are simple to add or revert.

As well, with Dat it's easy to make your content available on HTTP by having it hosted somewhere and many websites on the p2p web already do that.

Even if exokit support doesn't work out, the same content can be loaded in Beaker and in Firefox (with the dat-webext extension for Firefox nightly), so the content would still be available.

The benefits are that exokit will enable people to experiment with peer to peer VR spaces and potentially enable fully decentralized collaboration in VR which will improve onboarding for new developers by removing the need for setting up and maintaining servers.

Exokit seems to already be open to breaking changes, and this is less breaking than others

**Comment by ngokevin** [comment]
> improve onboarding for new developers by removing the need for setting up and maintaining servers

This isn't a thing, by the way. Hosting a web site is easy and free in 2018.

Will leave it to @modulesio 😛

**Comment by modulesio** [comment]
> Exokit seems to already be open to breaking changes, and this is less breaking than others

I think it's fine to break from things getting in the way of doing XR (the raison d'etre), but the goal is to enable rather than invent. I agree with @ngokevin that hosting is not a problem I see.

I'm fine with experimenting if the overhead is low (and I think it would be), but I think it would be equally appropriate to delete that experiment from mainline if it's not used and not maintained.

**Comment by RangerMauve** [comment]
Sorry, regarding hosting in that last part, I was referring to hosting servers that are needed to connect with others for collaboration. With the datPeers API, the same connections you use for decentralization can be used to broadcast stuff like movements in order to have multiplayer without any need for a centralized server like you would now.

As well, even though there are static file hosting solutions out there, they all have their own approaches and APIs that make it hard to integrate with within a VR app. With the DatArchive API you have a standard way to create and manipulate content with the added benefit of easily being able to fork and modify an existing archive. With the current web, it's up to companies that build products for this stuff to provide that capability, where as with the peer to peer web it's a fundamental building block that anyone has access to without restrictions.

I'm 100% in agreement that it would be easy to remove if people don't seem interested. I still strongly believe that it'll open up a lot of possibilities for things that can't be done on the current VR web without a central authority / company.

**Comment by modulesio** [comment]
This project doesn't use jsdom, at least not for the main nodes. It's just `parse5`.

Even if that were the case, I'd advocate for more control than using a resource loader api. The main place to intercept in our case is the `fetch` and `XMLHttpRequest`.

**Comment by RangerMauve** [comment]
My bad! Thanks for the clarification. 😁

Not sure what my ETA would be on working on this yet.

**Comment by RangerMauve** [comment]
@shaneharris Yeah, they're pretty similar. IPFS, Dat, and SSB seem to be the main JS-based p2p web things and they all have slightly different tradeoffs.

I'm focusing on Dat for this because it has a higher level of privacy out of the box by making it impossible to load your content unless a person has a copy of your URL, and it has a way of using versioned mutability so that people can quickly propogate updates to their VR worlds and users can potentially view older versions of a world.

**Comment by modulesio** [comment]
@RangerMauve I'm closing this issue until it gets external backing, because otherwise it probably doesn't fall on our roadmap.

Additionally there might be alternative approaches for distributed content loading on our end coming, with multi-site blending ("reality tabs") and url-less loading moving things away from a "browser" to an engine for WebXR.
