### ISSUE TITLE
Magic Leap API + docs

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#47]
We have supported the [Magic Leap simulator](https://creator.magicleap.com) for a while now. We will also support the real hardware when it ships!

However our approach/API exposition is not documented anywhere. We should clean up the API to conform to web expectations, with minimal deviation from WebXR, and then write up the documentation on https://docs.webmr.io 📖.

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated. Magic Leap docs can now be found at [magicleap.md](https://github.com/webmixedreality/exokit/blob/master/docs/magicleap.md).
