### ISSUE TITLE
Oculus HMD testing

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#48]
We don't have an Oculus headset in the office right now, though it _should_ be supported via [OpenVR](https://en.wikipedia.org/wiki/OpenVR).

It would be great if a volunteer could check if the basics work in the Oculus VR environment, and file any gotchas/bugs to the [main issue tracker on Github](https://github.com/webmixedreality/exokit/issue/new).

**Comment by modulesio** [comment]
The way to test this would be to just [download a release](https://get.webmr.io) and [enter VR by pressing `i`](http://docs.webmr.io/#/5minguide).

**Comment by modulesio** [comment]
Related: https://github.com/webmixedreality/exokit/issues/146

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated. Oculus progress is now being tracked in #146 and #787.
