### ISSUE TITLE
Magic leap WebAudio

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#484]
We have initial `WebAudio` hooked up on desktop, including microphone, but that's not the case on ML.

The API is pretty clean and compatible, just the buffer streaming bridge needs to be implemented.

**Comment by machenmusik** [comment]
(per discussion on #477, this seems to be the blocker)

**Comment by machenmusik** [comment]
Question, is someone working this issue at present, or if not can folks provide a few pointers as to where to dig in?

**Comment by modulesio** [comment]
I don't know of anyone doing it at the moment 🙏.

### Two parts
- webaudio bugs in the core (https://github.com/webmixedreality/exokit/pull/287, https://github.com/webmixedreality/exokit/issues/457)
- hooking up web audio streaming to magic leap lumin sdk

### Part 1

Nothing to do with magic leap, and more specific cases than general audio. Probably not needed for basic WebAudio on magic leap.

### Part 2 (hooking to MLSDK)

The latter is pretty straightforward and known. We would need to:
1. construct a magic leap audio context in [magic leap bindings]( https://github.com/webmixedreality/exokit/blob/master/deps/exokit-bindings/magicleap/src/magicleap.cc)
1. Change [LabSound realtime audio context](https://github.com/webmixedreality/exokit/blob/424694257a703f88e024ffa6dcc1c8656890d765/deps/exokit-bindings/webaudiocontext/src/AudioContext.cpp#L9) buffers to pipe to magic leap audio context

The latter might involve hooking in something deeper to [LabSound]( https://github.com/modulesio/LabSound/blob/f3618fa826bd917097d16a8eb4941424bb1ec73b/labsound/src/extended/LabSound.cpp#L29), which is the implementation of WebAudio that is built into [`native-audio-deps`](https://github.com/modulesio/node-native-audio-deps) (`require`d into exokit as [`nativeAudio`](https://github.com/webmixedreality/exokit/blob/424694257a703f88e024ffa6dcc1c8656890d765/src/native-bindings.js#L3))

**Comment by modulesio** [comment]
Closing as dupe of https://github.com/webmixedreality/exokit/issues/477, https://github.com/webmixedreality/exokit/issues/537.
