### ISSUE TITLE
Does not honor `once` option in addEventListener

### ISSUE THREAD

**Issue by 3DataWill** [webmixedreality/exokit#516]
https://glitch.com/edit/#!/dandy-jury?path=index.html:3:8

Expected behavior: 'myEvent Handled' logged exactly once

Observed behavior: 'myEvent Handled' logged every 100ms

**Comment by modulesio** [comment]
Thanks, I didn't know this was a thing. 👌

**Comment by ngokevin** [comment]
Oh wow, I also did not know this was a thing! No more self-removing event handlers.
