### ISSUE TITLE
WebGL2 support

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#52]
Exokit currently only supports the [`webgl` context](https://github.com/webmixedreality/exokit/blob/master/core.js#L2542). [WebGL2](https://www.khronos.org/registry/webgl/specs/latest/2.0/) adds a lot of nice stuff to that API.

Worry not! This actually is _much_ easier than it sounds; we already use [straight up OpenGL 3.2](https://github.com/webmixedreality/exokit/blob/383235ee0b81b1fc1dad0234b8db4be771e49618/deps/exokit-bindings/glfw/src/glfw.cc#L1051) for out WebGL backing, which is already a _superset_ of what we need for WebGL2. So implementing WebGL2 would be mostly a matter of exposing/defaulting functionality in Javascript per the spec, rather than implementing much native code.

We should try to follow the WebGL/WebGL2 exposure rules in the spec as much as possible.

**Comment by modulesio** [comment]
Been needing some of thee methods lately since emscripten uses it.

**Comment by Palmer-JC** [comment]
Frameworks like Babylon.JS first try to create a webgl2 context.  If that fails, then a webgl context is created.
I see that you are transpiling webgl1 to webgl2 shaders.  

Might not even bothering to transpile be another way?

**Comment by Palmer-JC** [comment]
Sorry, I did not see that this was closed.  I have a [test scene](https://palmer-jc.github.io/scenes/QueuedInterpolation/mesh_parent/index_pbr.html), which has other problems I was going to put in a separate issue, but the first line in the console is the context created. 

On a browser, it says 2, but on exokit it says 1.

**Comment by modulesio** [comment]
I'll reopen this in that case. Do you know which part of Babylon is deciding it's only WebGL1 supported?

**Comment by Palmer-JC** [comment]
Pretty sure webgl2 is tried first, [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Engines/engine.ts#L1072), and then webgl is try next.

Also, I see exceptions for certain browsers, [here](https://github.com/BabylonJS/Babylon.js/blob/master/src/Engines/engine.ts#L240).

**Comment by Palmer-JC** [comment]
You might have saw the test to make sure that query was supported before accepting the WebGL2 context for use, and assumed that was the issue (I did).  I just put that to the test by commenting it out.  Still no WebGL 2 context.

In fact, I do not believe you can get a WebGL2 context, no matter what you do.  I wrote a self contained page, which all it does was create a context.  It fails trying to create context:

```
<html>
<head>
    <meta charset="UTF-8">
    <title>Test exokit webgl2</title>

    <style>
         html, body   { width: 100%; height: 100%; margin: 0; padding: 0; overflow: hidden; }
         #renderCanvas{ width: 100%; height: 100%; }
    </style>
</head>
<body>
<canvas id="renderCanvas"></canvas>
<script>
    const canvas = document.getElementById("renderCanvas");
    var gl;
    try {
        gl = (canvas.getContext("webgl2") || canvas.getContext("experimental-webgl2"));
        if (gl) {
            console.log("webGL 2 context created");
        }
    }
    catch (e) {
        console.log('webgl 2 failed because: ' + e);
    }

    if (!gl) {
        try {
            gl = (canvas.getContext("webgl") || canvas.getContext("experimental-webgl"));
        }
        catch (e) {
            throw new Error("WebGL not supported");
        }
    }
    if (gl) {
        console.log("consolation prize of webGL 1 context created");
    } else throw new Error("WebGL not supported");
        

</script>
</body>
</html>
```

The console said:
```
webgl 2 failed because: ReferenceError: WebGLRenderingContext is not defined
consolation prize of webGL 1 context created
```

**Comment by modulesio** [comment]
Definitely a regression in that case. The webgl/webgl2 contexts are the
same thing under the hood but we should still be able to use both apis.

**Comment by Palmer-JC** [comment]
can now be closed

**Comment by modulesio** [comment]
Thanks for the reminder; closing in favor of https://github.com/webmixedreality/exokit/pull/775.
