### ISSUE TITLE
Leap Motion examples

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#53]
We already have [Magic Leap](https://github.com/webmixedreality/exokit/blob/383235ee0b81b1fc1dad0234b8db4be771e49618/deps/exokit-bindings/magicleap/src/magicleap.cc) + [Leap Motion](https://github.com/webmixedreality/exokit/blob/383235ee0b81b1fc1dad0234b8db4be771e49618/deps/exokit-bindings/leapmotion/src/leapmotion.cc) APIs in the code 🎉. However, what we're lacking is site examples showcasing the awesomeness within.

There's some of this stuff in [our fork of THREE.js](https://github.com/webmixedreality/three.js/examples).

In particular;
- [Exokit home supports Leap Motion hands](https://github.com/webmixedreality/exokit-home)
- [Magic Leap - R2 vs BB8](https://github.com/webmixedreality/three.js/blob/dev/examples/webgl_demo_robots.html)

We could use more examples, as well as a structured place to publish them. Either a site or a dedicated repository.

**Comment by chrislatorres** [comment]
There are now a lot of examples for the Magic Leap API in the [examples directory](https://github.com/webmixedreality/exokit/tree/master/examples).
