### ISSUE TITLE
ML: not sure MutationObserver is working?

### ISSUE THREAD

**Issue by machenmusik** [webmixedreality/exokit#582]
Working on a crude alternative implementation for hear what I hear, since ML is deprecating the proper API, I wrote some code based on MutationObserver to run when audio elements are created / attached / detached.  However, that code does not seem to run correctly on ML with Exokit.  (document.body observer...)

**Comment by modulesio** [comment]
Can you provide a reproduction? Which part is not correct?

**Comment by modulesio** [comment]
Closing this because there are no reproduction steps -- please re-open if there are.
