### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#6]
Need to mention:

#### Requirements
- `windows-build-tools`
- MagicLeap building
- Node 9

#### Build methods
- `npm i exokit`
- Github Releases
- manual build

**Comment by modulesio** [comment]
CC @Fierent the place for this is the docs? Or readme? Or both?

**Comment by modulesio** [comment]
```
> 8:39 <@fierent> oh on #6 where you tagged me for the issues, I think it should go on both the docs and readme because its that important imo
```

**Comment by TrevorDev** [comment]
To get this to work on windows
I installed node version v10.8.0 (9 like mentioned above did not seem to work)
cloned this repo
npm install
exokit.cmd -h -l

**Comment by modulesio** [comment]
Thanks!
