### ISSUE TITLE
Animation is on fast forward.

### ISSUE THREAD

**Issue by trusktr** [webmixedreality/exokit#614]
Hello, I just tried this demo, https://threejs.org/examples/webgl_animation_cloth.html, and the cloth animates very very fast.

Is that expected on that demo? Is it perhaps relying on the fact that regular browsers limit the frame rate to 60fps?

**Comment by modulesio** [comment]
I see the same thing, and this is expected judging from the simulation implementation, which is dependent on the tick rate (https://threejs.org/examples/js/Cloth.js).

Any example that does a constant thing every frame without diffing timestamps would be subject to this (similar problems with VR).

Closing this as I don't think it's an Exokit issue.

**Comment by modulesio** [comment]
I wonder if it would make sense to cap to 60 to do something that's more expected from a browser though...
