### ISSUE TITLE
Can't install exokit in MacOS

### ISSUE THREAD

**Issue by NoSilver2018** [webmixedreality/exokit#618]
I tried to install Exokit using npm. However, the following error occurred.   How can I install it?
![issue](https://blogfiles.pstatic.net/MjAxODExMjVfMjU1/MDAxNTQzMTMzNDgyNTAy.tVcZ6CWCWyWrnuFgTnWqvE7nxDjnmWzzY-M7A2oYI7Ag.0aHIyJVSug076NQVLXmGwT723PvTmnn4OGxnCdFMF0Ag.PNG.shdmsrla/issue.png)
)

**Comment by modulesio** [comment]
Looks like there was an error listed above. Could you post the full build log from npm?

**Comment by modulesio** [comment]
Also, it looks like you’re using node 11.2.0. Currently only node 10 is supported. 

There is a multithreading refactor for node 11.2.0 in progress but it is not in master yet.

**Comment by modulesio** [comment]
Please re-open this issue if you get the same thing with node `10`!
