### ISSUE TITLE
Unable to use filereader.readAsText

### ISSUE THREAD

**Issue by extraymond** [webmixedreality/exokit#623]
## Description

Hi! I've been toying around with exokit for awhile and like it so far. Here's is a thing I found during messing with it.

In the exokit runtime, while being able to create a filereader, it won't allow me to run the following code:

```javascript
let fs = new FileReader()
fs.addEventListener('load', e=> {

    processing logic here...


    console.log(e)}
)

fs.readAsText()
```

The error is:
> TypeError: fs.readAsText is not a function

---

## Configuration

exokit: 0.0.495 (installed via CLI)
os: ubuntu 18.04 64bit
content: custom aframe-website

**Comment by modulesio** [comment]
Thanks, looks like the JS just doesn't implement it here: https://github.com/webmixedreality/exokit/blob/5f15e7a39ee23139005940523928a38baf18b6a5/src/core.js#L579

**Comment by extraymond** [comment]
@modulesio  Thx for your reply. This makes sense now.

I was curious to know whether exokit is built on-top of node or something else, since node didn't support FileReader api natively either. 

Are there plans to be compatible to the browser spec? Since I assume exokit is more like a intermediate layer for contents written directly for webvr(which is targeting browsers mostly)
If no, It would be nice to know it in the docs.

Glad to know it is indeed implemented in a different way. Guess this is for performance reasons?
Once again, thx for making this wonderful project.
