### ISSUE TITLE
slack inviter quota exceeded

### ISSUE THREAD

**Issue by micahstubbs** [webmixedreality/exokit#650]
![screenshot_20181217-094215](https://user-images.githubusercontent.com/2119400/50104915-1baaef00-01e0-11e9-994f-dd83fe4bc133.jpg)

**Comment by micahstubbs** [comment]
maybe try a different auto invite service or pay this one for more quota?

**Comment by modulesio** [comment]
Thanks for finding that Micah, we're actually not using that link anymore. I updated the `README.md` to reflect: https://github.com/webmixedreality/exokit/commit/ffc0d4d7385c36d1f4533e95d0c7fa312f1fe805

The link should be https://join.slack.com/t/exokit/shared_invite/enQtNDI3NjcxNzYwMDIxLWU2NmFmOTEzMzk4NWNiYjRhMjVkYzcyNjg5YjUyMzZkYWM1ZGI4M2IwYWZiMjNlMTJjMDlkM2U3Y2JiNTc2M2Q

**Comment by modulesio** [comment]
I'm closing this as resolved; LMK the community inviter link exists elsewhere. 😅
