### ISSUE TITLE
Feature request: keys to open console

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#660]
Exokit has shell support, as well as `ndb`, but it's hidden behind a shell invocation. It would be nice to have a Ctrl-Shift-I type hotkey to open a command console or debugger to debug the current app.

**Comment by modulesio** [comment]
I did some reasearch + prototyping and the best path forward for this seems to be a light custom UI +  terminal (`hterm`), exposing [`chrome-remote-interface`](https://github.com/cyrus-and/chrome-remote-interface) directly connected to Exokit's `node`.

Would like to use actual chrome devtools here, but unfortunately the frontend is very tied to chrome itself.

**Comment by modulesio** [comment]
Also, this was suggested as being a good complement to a multi-app reality tabs environment, allowing each reality tab to be debugged in place in the world.

**Comment by chrislatorres** [comment]
This seems to have been implemented in #670.

**Comment by modulesio** [comment]
Yeah. Devtools needs work but that's probably the right framework of discussion for this feature request.
