### ISSUE TITLE
Canvas.toDataURL is not base64 encoded

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#704]
calling toDataURL and logging the result gives the below:

```
data:image/png;base64,�PNG

    �Om
�╝\ ╔+.��    IEND�B`�
```
there is a base64 function here - https://github.com/ReneNyffenegger/cpp-base64 would that be suitable do you think? I can cut a PR if you think that one could work.

**Comment by shaneharris** [comment]
By Buffer do you mean skia? Like this - https://github.com/google/skia/blob/41a5eaca8b95fba832e4a403889163c65bcca770/src/svg/SkSVGDevice.cpp#L431-L436 ?

**Comment by shaneharris** [comment]
I've been looking around and i cant find what you mean but if you can point me at it ill get stuck in

**Comment by modulesio** [comment]
Yeah, presumably the data comes in as an ArrayBuffer, from which we can do toString(“base64”)

**Comment by modulesio** [comment]
Actually I see this is done by Skia: https://github.com/webmixedreality/exokit/blob/master/deps/exokit-bindings/canvascontext/src/canvas-context.cc#L1259

So we could probably get this as an ArrayBuffer (therefore implementing [`toBlob`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob)), and use `Buffer` to convert that to a `base64` string.

**Comment by shaneharris** [comment]
I had exactly the same thought, i had a branch but had some problems sending the buffer back. I see you have it in hand though :)
