### ISSUE TITLE
Reporting non-existing controllers

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#723]
Currently `gamepads.length` = 2 and `inputSources.length` = 2 because 2 controllers are reported by default:

https://github.com/webmixedreality/exokit/blob/1956ca422ed86842370163abb27311948c101119/src/core.js#L1770-L1771
-->
https://github.com/webmixedreality/exokit/blob/76e5d7888dcf49487288cc185c88e4503b45fef3/src/VR.js#L487-L499  
  
and
  
https://github.com/webmixedreality/exokit/blob/726a0d5e3247c80c048c65875a0eb49392efc1d7/src/XR.js#L118-L121
  

Visual of extra controllerMesh/rayMesh in an example due to non-existing controller reported:
![dwmwd-qvaaertem](https://user-images.githubusercontent.com/29695350/51048301-3dee1d80-1590-11e9-911d-c4a73969d8c1.jpg)

**Comment by modulesio** [comment]
There is the [connected](https://developer.mozilla.org/en-US/docs/Web/API/Gamepad/connected) property but exokit doesn’t set it.

That’s probably the easy win here and it’s easy enough to add in the bindings.

The examples also need to be updated to not create these apuriois controller meshes.

**Comment by chrislatorres** [comment]
I see https://w3c.github.io/gamepad/#widl-Gamepad-connected
>  boolean connected
> Indicates whether the physical device represented by this object is still connected to the system. When a gamepad becomes unavailable, whether by being physically disconnected, powered off or otherwise unusable, the connected attribute MUST be set to false. 
  
    
Looks like there is a connected property, but it is set to true by default:

https://github.com/webmixedreality/exokit/blob/76e5d7888dcf49487288cc185c88e4503b45fef3/src/VR.js#L113
  
-------------------------------------------------
  
There is a bool `is_connected` for `MLInputControllerState`[0] that could be added to determine if ml controller is connected  https://github.com/webmixedreality/exokit/blob/1267da4dd3262df01c5cd705c5e0350edd1ddf4b/deps/exokit-bindings/magicleap/src/magicleap.cc#L2856 

----------------------------------------------
  
  
Where to add bool to gamepads:
  
  https://github.com/webmixedreality/exokit/blob/1956ca422ed86842370163abb27311948c101119/src/index.js#L1439
https://github.com/webmixedreality/exokit/blob/1956ca422ed86842370163abb27311948c101119/src/index.js#L1448
  
------------------------------------------------
[0] https://creator.magicleap.com/learn/reference/public/v0.19.0/CAPI/ml__input_8h.html
