### ISSUE TITLE
Reality tabs: colon

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#772]
The colon key on the virtual keyboard does not respond to controller presses in the url bar; it probably has the wrong key code.

**Comment by NoahSchiffman** [comment]
So is this the reason why If I press the arrow it makes some weird code?

**Comment by modulesio** [comment]
@NoahSchiffman Is that re: the virtual keyboard, or physical keyboard events? Was there a separate issue that should be filed there?

**Comment by NoahSchiffman** [comment]
not so sure, I think it was filed as a bug but I'm not sure which it's probably fixed! I would ordinarily press the "+" icon and would get something along the lines of such a url I could not read back to you atm but is very long. usually the same.

**Comment by chrislatorres** [comment]
Just tested on device and this issue has been resolved.
