### ISSUE TITLE
A-Blast scaling relative to Reality Tabs menu

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#808]
Exokit v0.0.517
Ubuntu 18.04
Node v11.6.0 

A-Blast is working other than the scaling being off relative to the Reality Tabs menu:

![screenshot from 2019-03-05 18-13-47](https://user-images.githubusercontent.com/29695350/53846649-659ba980-3f73-11e9-93f7-68d71abc2703.png)

--------------------------------------------------

Without Reality Tabs, the scaling is normal: 

![screenshot from 2019-03-05 18-22-07](https://user-images.githubusercontent.com/29695350/53846729-a4316400-3f73-11e9-9910-af7de77dd1ea.png)

**Comment by chrislatorres** [comment]
The scaling behavior is similar for a-painter:

![screenshot from 2019-03-05 18-45-14](https://user-images.githubusercontent.com/29695350/53847572-dc867180-3f76-11e9-9b88-e035913ca2a0.png)
![screenshot from 2019-03-05 18-47-03](https://user-images.githubusercontent.com/29695350/53847623-16f00e80-3f77-11e9-8fe6-ab94e621fc64.png)

**Comment by modulesio** [comment]
Looks like a canvas sizing issue.

**Comment by chrislatorres** [comment]
Noticed that there is an edge where the Reality Tab content is "cut off" on desktop, see exobot:

![screenshot from 2019-03-05 19-05-23](https://user-images.githubusercontent.com/29695350/53848478-186f0600-3f7a-11e9-89eb-822164e3f0c1.png)

**Comment by chrislatorres** [comment]
A better visual of how the content cut off:
![screenshot from 2019-03-05 19-30-17](https://user-images.githubusercontent.com/29695350/53849356-25d9bf80-3f7d-11e9-854e-8fe7d4125ecc.png)

**Comment by modulesio** [comment]
This isn't unique to the reality tabs case; I just saw it in Vive as well on `master`.

**Comment by chrislatorres** [comment]
Fixed by #828 
![Screenshot from 2019-03-08 18-45-28](https://user-images.githubusercontent.com/29695350/54063520-6a11cd80-41d2-11e9-8c9b-91d1f2d21451.png)

**Comment by modulesio** [comment]
I think the Vive case is separate, and relates to max multisampled texture sizes.
